# Generated by Django 3.1.2 on 2020-11-02 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EMImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', upload_to='Input/')),
                ('mask', models.FileField(blank=True, upload_to='Mask/')),
                ('particle_groups', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('trained_model', models.CharField(choices=[('43kGoldDigger', '43kGoldDigger'), ('87kGoldDigger', '87kGoldDigger')], default='87kGoldDigger', max_length=100)),
                ('gold_particle_coordinates', models.FileField(null=True, upload_to='analyzed/coordinates')),
                ('analyzed_image', models.ImageField(null=True, upload_to='analyzed/images')),
                ('histogram_image', models.ImageField(null=True, upload_to='analyzed/histograms')),
            ],
        ),
    ]
