# Generated by Django 3.1.3 on 2020-12-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='coordinates6nm',
            field=models.FileField(null=True, upload_to='analyzed/coordinates6nm'),
        ),
    ]
