# Generated by Django 3.1.1 on 2020-09-30 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Member',
        ),
    ]
