# Generated by Django 3.1.3 on 2020-12-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0002_emimage_coordinates6nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='chunked_file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
