# Generated by Django 3.1.3 on 2020-12-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0002_emimage_coordinates6nm'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='threshold_string',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
