# Generated by Django 3.1.3 on 2020-12-09 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chunked_upload', '0001_initial'),
        ('GDapp', '0003_emimage_chunked_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='chunked_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chunked_upload.chunkedupload'),
        ),
    ]
