# Generated by Django 3.1.2 on 2020-10-20 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0003_auto_20201014_1742'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='EMImage',
        ),
        migrations.RenameField(
            model_name='emimage',
            old_name='profile',
            new_name='image',
        ),
    ]
