# Generated by Django 3.1.3 on 2020-12-09 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0004_emimage_chunked_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emimage',
            old_name='chunked_file_path',
            new_name='chunked_image_id',
        ),
        migrations.RemoveField(
            model_name='emimage',
            name='chunked_file',
        ),
        migrations.AddField(
            model_name='emimage',
            name='chunked_mask_id',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
