# Generated by Django 3.1.2 on 2020-10-20 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0004_auto_20201020_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='trained_model',
            field=models.CharField(choices=[('43kGoldDigger', '43kGoldDigger'), ('87kGoldDigger', '87kGoldDigger')], default='87kGoldDigger', max_length=100),
        ),
    ]
