# Generated by Django 3.1.2 on 2020-10-22 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0005_emimage_trained_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='mask',
            field=models.FileField(blank=True, upload_to='Mask/'),
        ),
    ]
