# Generated by Django 3.1.3 on 2020-12-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0006_emimage_chunked_image_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='preloaded_pk',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
