# Generated by Django 3.1.4 on 2020-12-10 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0007_emimage_preloaded_pk'),
        ('GDapp', '0003_emimage_threshold_string'),
    ]

    operations = [
    ]
