# Generated by Django 3.1.4 on 2020-12-10 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0007_emimage_preloaded_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
