# Generated by Django 3.1.2 on 2020-10-26 17:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0007_emimage_particle_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimage',
            name='particle_groups',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
