# Generated by Django 3.1.1 on 2020-10-28 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0008_auto_20201026_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimage',
            name='image',
            field=models.FileField(blank=True, upload_to='Input/'),
        ),
    ]
