# Generated by Django 3.1.1 on 2020-10-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0009_auto_20201028_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimage',
            name='image',
            field=models.FileField(blank=True, default='', upload_to='Input/'),
        ),
    ]
