# Generated by Django 3.1.4 on 2020-12-11 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0009_auto_20201210_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emimage',
            name='coordinatesGroup1',
        ),
    ]
