# Generated by Django 3.1.4 on 2020-12-15 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0008_emimage_created_at'),
        ('GDapp', '0010_remove_emimage_coordinatesgroup1'),
    ]

    operations = [
    ]
