# Generated by Django 3.1.2 on 2020-10-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0010_auto_20201029_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='analyzed_image',
            field=models.ImageField(null=True, upload_to='analyzed_spines/images'),
        ),
        migrations.AddField(
            model_name='emimage',
            name='gold_particle_coordinates',
            field=models.FileField(null=True, upload_to='analyzed_spines/coordinates'),
        ),
    ]
