# Generated by Django 3.1.2 on 2020-10-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0011_auto_20201029_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='histogram_image',
            field=models.ImageField(null=True, upload_to='analyzed/histograms'),
        ),
        migrations.AlterField(
            model_name='emimage',
            name='analyzed_image',
            field=models.ImageField(null=True, upload_to='analyzed/images'),
        ),
        migrations.AlterField(
            model_name='emimage',
            name='gold_particle_coordinates',
            field=models.FileField(null=True, upload_to='analyzed/coordinates'),
        ),
    ]
