# Generated by Django 3.1.4 on 2021-01-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0015_localfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalFile',
        ),
        migrations.AddField(
            model_name='emimage',
            name='local_file',
            field=models.FilePathField(default='', path='/usr/src/local-images'),
            preserve_default=False,
        ),
    ]
