# Generated by Django 3.1.4 on 2021-01-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0017_auto_20210121_1918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emimage',
            old_name='local_file',
            new_name='local_image',
        ),
        migrations.AddField(
            model_name='emimage',
            name='local_mask',
            field=models.FilePathField(default='', path='/usr/src/local-images'),
        ),
    ]
