# Generated by Django 3.1.4 on 2021-01-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0019_auto_20210121_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimage',
            name='local_image',
            field=models.FilePathField(blank=True, path='/usr/src/local-images'),
        ),
        migrations.AlterField(
            model_name='emimage',
            name='local_mask',
            field=models.FilePathField(blank=True, path='/usr/src/local-images'),
        ),
    ]
