# Generated by Django 3.1.4 on 2021-02-04 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0020_auto_20210121_1936'),
        ('GDapp', '0014_auto_20210204_1524'),
    ]

    operations = [
    ]
