# Generated by Django 3.1.4 on 2021-02-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0021_merge_20210204_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimage',
            name='threshold_string',
            field=models.CharField(blank=True, default='1, 300', max_length=200),
        ),
    ]
