# Generated by Django 3.1.4 on 2021-03-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0022_auto_20210204_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='emimage',
            name='thresh_sens',
            field=models.FloatField(default=4.0),
        ),
    ]
