# Generated by Django 3.1.4 on 2021-03-22 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0014_auto_20210222_1955'),
        ('GDapp', '0023_emimage_thresh_sens'),
    ]

    operations = [
    ]
