# Generated by Django 3.1.4 on 2021-04-05 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0026_auto_20210325_1433'),
        ('GDapp', '0024_merge_20210322_2009'),
    ]

    operations = [
    ]
