# Generated by Django 3.1.4 on 2021-04-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0026_auto_20210325_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimage',
            name='trained_model',
            field=models.CharField(choices=[('43kGoldDigger', 'GoldDigger for small particles in 43k images'), ('87kGoldDigger', 'General GoldDigger (87k)'), ('greenonly_041421', 'Green Only GoldDigger (04/14/2021)'), ('balanced_041421', 'Balanced GoldDigger (04/14/2021)')], default='87kGoldDigger', max_length=100),
        ),
    ]
