# Generated by Django 3.1.4 on 2021-04-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0028_auto_20210405_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimage',
            name='thresh_sens',
            field=models.FloatField(default=4.0),
        ),
    ]
