# Generated by Django 3.1.4 on 2021-04-22 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0033_auto_20210421_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimage',
            name='threshold_string',
            field=models.CharField(blank=True, default='1, 60', help_text='Input comma-separated values to serve as the lower and upper boundaries for the area of each particle size.', max_length=200),
        ),
        migrations.AlterField(
            model_name='emimage',
            name='trained_model',
            field=models.CharField(choices=[('43kGoldDigger', 'GoldDigger for small particles in 43k images'), ('87kGoldDigger', 'General GoldDigger (87k)'), ('greenonly_041421', 'Green Only GoldDigger (04/14/2021)'), ('balanced_041421', 'Balanced GoldDigger (04/14/2021)')], default='87kGoldDigger', max_length=100),
        ),
    ]
