# Generated by Django 3.1.4 on 2021-04-23 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0027_auto_20210420_1419'),
        ('GDapp', '0034_auto_20210422_1548'),
    ]

    operations = [
    ]
