# Generated by Django 3.1.4 on 2021-04-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0035_merge_20210423_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimage',
            name='local_mask',
            field=models.FilePathField(blank=True, default=None, path='/usr/src/local-images'),
        ),
    ]
