# Generated by Django 3.1.4 on 2021-04-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0037_auto_20210423_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emimage',
            name='trained_model',
            field=models.CharField(choices=[('43kGoldDigger', 'GoldDigger for small particles in 43k images'), ('87kGoldDigger', 'General GoldDigger (87k)'), ('greenonly_041421', 'Green Only GoldDigger (04/14/2021)'), ('balanced_041421', 'Balanced GoldDigger (04/14/2021)'), ('greenonly_0422', 'Corrected Images: Green Only GoldDigger (04/22/2021)'), ('balanced_0422', 'Corrected Images: Balanced GoldDigger (04/22/2021)')], default='87kGoldDigger', max_length=100),
        ),
    ]
