# Generated by Django 3.1.4 on 2021-04-29 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GDapp', '0038_auto_20210423_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emimage',
            name='chunked_image_id',
        ),
        migrations.RemoveField(
            model_name='emimage',
            name='chunked_image_linked',
        ),
        migrations.RemoveField(
            model_name='emimage',
            name='chunked_mask_id',
        ),
    ]
